name: Run tests on the PR and trigger to write the documentation

concurrency:
  group: run-test-${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true


on:  
  push:
    branches:
      - chore/added-test
  pull_request:
    branches:
      - main

jobs:
  pr-test:
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v3

      - name: Check for contract changes
        id: check-contracts
        run: |
          git fetch --unshallow || true
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | grep -q "^contracts/" || echo "::set-output name=changes::false"
          else
            git diff --name-only HEAD^ HEAD | grep -q "^contracts/" || echo "::set-output name=changes::false"
          fi
        continue-on-error: true

      - name: Skip if no contract changes
        if: steps.check-contracts.outputs.changes == 'false'
        run: |
          echo "No changes in contracts directory, skipping..."
          exit 0

      - uses: actions/setup-node@v3
        if: steps.check-contracts.outputs.changes == 'true'
        with:
          node-version: 18
          
      # - run: yarn install

      # - run: yarn test

      - run: echo "hihi haha 2" >> test.txt
        if: steps.check-contracts.outputs.changes == 'true'

      - name: Create new branch and push the document
        if: steps.check-contracts.outputs.changes == 'true'
        run: |
          set -e

          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

          git add .
          git commit -m "Add documentation for PR"
          git push origin

          echo "Pushed the documentation to the branch"

