name: Run tests on the PR and trigger to push the documentation back

on:  
  push:
    branches:
      - chore/added-test
  pull_request:
    branches:
      - main

jobs:
  pr-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      # - run: yarn install     # TODO: enable this back
      # - run: yarn test
      - run: echo "hihi haha" > test.txt
      - name: Create new branch and push the document
        run: |
          set -e

          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

          git add .
          git commit -m "Add documentation for PR ${{ github.event.pull_request.number }}"
          git push origin

          echo "Pushed the documentation to the branch"

