name: Run tests on the PR and trigger to push the documentation back

on:  
  push:
    branches:
      - chore/added-test
  pull_request:
    branches:
      - main

jobs:
  pr-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      # - run: yarn install     # TODO: enable this back
      # - run: yarn test
      - name: Create new branch and push the document
        run: |
          set -e

          export pr_number=${{ github.event.pull_request.number || github.sha }}
          
          # new_doc_branch=$(echo "doc/${pr_number}")
          
          new_doc_branch=doc/me
          # TODO

          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git branch -D $new_doc_branch || true
          git checkout -b $new_doc_branch
          
          echo "hihi" > doc.md

          git add .
          git commit -m "Add documentation for PR ${{ github.event.pull_request.number }}"
          git push origin $new_doc_branch
          git log --oneline -n 5
          echo "Pushed the documentation to the branch $new_doc_branch"

      - name: Create a pull request for the documentation
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.CICD_BOT_TOKEN }}
          commit-message: Add documentation for PR ${{ github.event.pull_request.number }}
          title: Add documentation for PR ${{ github.event.pull_request.number }}
          body: |
            This pull request adds documentation for PR ${{ github.event.pull_request.number }}.
          
          branch: doc/me
          # branch: doc/${{ github.event.pull_request.number || github.sha }}
          
          # base: ${{ github.head_ref }}
          base: chore/added-test  # for debugging purpose


          # TODO: request for the comment to be resolved
